config/routes.rb
Vmeal::Application.routes.draw do

  root :to => "home#index"

  get "test/index"

  get "qingans/index"

  get "qingan/index"

  resources :score_histories, :only=>[:index,:new,:create]
  resources :activities, :only=>[:index,:show]
  namespace :admins do
    resources :stores, :store_users, :orders, :emails,:notices,:phone_lists,:schools
    resources :users do
      collection do
        post "query" => "users#query"
        get "export" => "users#export", :as=>"export"
        post "do_export"=>"users#do_export"
      end
      get "history/(:id)" => "users#history" ,:as=>"history"
      get "is_locked/(:id)" => "users#is_locked" ,:as=>"is_locked"
    end
    resources :ads do
      collection do
        post "query" => "ads#query"
      end
      get "is_locked" => "ads#is_locked" ,:as=>"is_locked"
    end
    resources :station_mails do
      collection do
        get "send_mail"
        get "new_user"
      end
    end

    resources :messages do
      collection do
        get "is_locked/(:type)/(:id)" =>"messages#is_locked"
        post "query" => "messages#query"
      end
    end
    resources :vmails do
        collection do
            get "sent_now"=>"vmails#sent_now"
        end
     end
    resources :activities do
        collection do
            get "kaijiang/(:id)" =>"activities#kaijiang"
        end
    end

  end

  resources :admins  do
    collection do
      get "finance"
      get "login"=>"admins#login"
      get "logout"=>"admins#logout"
    end
  end

  resources :station_mails do
    collection do
      get 'send_mail'
    end
  end

  get "notices/:id"=>"notices#show"


  resources :integral_consumer_records do
    collection do
      get "change_status"
    end
  end

  resources :logistics do
    collection do
      get "center"
      get "orderinfo"
      get "login"
      get "history"
      post "islogin"
      get "changeorder"
      get "filedorder"
    end
  end

  resources :order_manager do
    collection do
      get "midify_status"
      get "set_be_watered"
      post "search"
      get "set_user_is_ok"
      get "destroy1"
      get 'has_order'
      get 'has_store_order'
    end
  end

  resources :qingans

  get 'pc/i_want'

  resources :applications do
    collection do
      get "list_all_my_applications"
      get "sh"
      get 'succuss'
      get 'failure'
    end
  end

  resources :fs_manager do
    collection do
      get "change_status"
      get "destroy1"
    end
  end

  get "season_foods/:id/show" =>"season_foods#show"

  resources :super_market do
    member do
      get 'show'
    end
  end

  post "/complaints/do_complaint" =>"complaints#do_complaint"

  resources :messages

  resources :send_addresses

  resources :home ,:only =>[:index] do
    collection do
      get "show_stores"
      get 'qingan' => "home#qingan", :as => :qingan
      post 'signup'
    end
  end
  get "/sina" => "home#sina"

  get "about_us/(:type)" => "about_us#about_link", :as => :about_us

  resources :season_foods

  resources :sto_categories
  resources :send_addresses

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :sessions => "sessions"
  }

  devise_scope :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    collection do
      get 'qqlogin'
      get 'sina_login'
      get 'get_user_qq_info'
      get 'center'
      get 'destory_favorite_food'
      get 'destory_favorite_store'
      get 'destory_user_address'
      get 'left'
      get 'person_center'
      get 'person_center_avatar'
      get 'person_center_order_history'
      get 'person_center_order_uncomment'
      get 'person_center_fav_food'
      get 'person_center_integral'
      get 'person_center_comment'
      get 'person_center_message'
      get 'person_center_fav_store'
      get 'person_center_address'
      get 'person_center_address_new'
      get 'person_center_password'
      get 'destory_favorite_food'
      get 'destory_favorite_store'
      get 'destory_address/:address_id'=>"users#destory_address",:as=>:destory_address
      get 'register_email'
      get 'set_default_address'
      get 'person_center_info'
      get 'bill'
      get 'user_complaints'
      get 'do_complaint'
      get 'do_one_complaint'
      get 'send_addresses_new'
      get 'do_com' =>'users#do_one_order_comment'
      get 'change_line_item_quantity'
      post 'create_user_weibo'
      post 'is_login_in_uid'
      post 'save_com' =>'users#save_order_comment'
      get 'eat_one'
      get 'resend_email'
      get 'send_email'
      get 'bill_empty'
      get 'integral_bill'
      get 'create_exchange_good'
      get 'change_exchange_good_number'
      get 'integral_bill_empty'
      get 'person_center_integral_history'
      get 'home'=>"users#personal_basic"
      get 'address'=>"users#personal_address"
      get 'collects'=>"users#personal_collect",:as=>:collects
      get 'mails/:status'=>"users#personal_mail",:as=>:mails
      get 'orders/:status'=>"users#personal_order",:as=>:orders
      get 'account'=>"users#personal_account"
      get 'create_message'
      get 'read_mail'
      get 'delete_mail'
      get 'stores_manage'
      get 'drop_order'
      get 'score_histories/(:type)'=>"users#score_histories",:as=>:score_histories,:constraints => { :type => /add|sub|/ }
      get 'welfare/(:type)'=>"users#welfare"
      post 'welfare/address_create' =>"users#good_address_create"
      get "qiandao"=>"users#qiandao"
    end
  end

  resources :orders ,:only=>[:new,:create,:destroy,:show]

  resources :line_items ,:only=>:create do
    collection do
      post 'modify/:task'=>"line_items#modify",:as=>:modify
    end
  end

  resources :orders do
    collection do
      get 'apply_fail_order'
      get 'do_fail_order'
      get 'recover_order'
    end
  end

  resources :foods do
    collection do
      get "add_favorite_foods"
      get "search"
      get 'add_recomment'
    end
  end

  resources :categories do
    resources :foods
  end

  resources :stores  ,:only=>[:show] do
    collection do
      get "add_fav_store"
      get 'cancel_fav_store'
      get 'edit/(:type)'=>"stores#edit",:as=>:edit
      get 'open'
      get 'close'
      get 'delete_food'
      get 'login'
      get 'logout'
      get 'order_details'
      get 'delete_category'
      get 'cancel_ad'
      get 'order_success'
      get 'has_new_order/(:store_id)/(:max_order_id)'=>"stores#has_new_order"
    end
  end

  resources :reply, :only=>[:show,:create]

  get "stores/:id/delete"=>"stores#destroy"

  post "serarch"=>"foods#serarch"

  post "otherlogin" => "users#otherlogin"

  get "stores/:id/delete"=>"stores#destroy"

  post "carts/action/:type" => "carts#action"

  get 'cj/:type', to: "activities#index", constraints: { type:  /coming|history/ }
  get 'cj/:id', to: "activities#show", constraints: { :id => /\d+/ }
  resources :score_histories
  get 'cj/confirm_order'=>"score_histories#new"
  get 'cj/error'=>"score_histories#error"
  get 'faq/jf_rule' => "faq#jf_rule"
  get 'locate' => 'home#location'
  get 'choose/(:id)' => 'home#set_location'
end

app/models/store.rb
# encoding: utf-8
class Store < ActiveRecord::Base

  STORE_STATUS = ["营业","打烊"]
  STORE_STATUS_ADMIN_HASH = { 0 => "营业",  1 => "打烊" ,   2 => "退出平台"}

  STORE_TAGES = ["便宜","川菜","环保","韩式","辣的爽"]
  STORE_TYPE = {0 => "网络商家", 1 => "电话商家", 2 => "更多商家"}
  validates :isclose,  :rank, :presence => true , :presence =>{:message =>"此内容不能为空"}
  validates :name, :length =>{ :maximum => 50,:message =>"店家名称不能超过了10个字符"},
  :presence =>{:message =>"店家名称不能为空"}
  validates :isclose, :numericality =>{:only_integer => true,
    :greater_than_or_equal_to =>0,
    :less_than_or_equal_to =>2,
  }
  # attr_accessible :order_periods_attributes
  # attr_accessible :name, :order_periods_attributes
  validates :send_price, :numericality =>{:greater_than_or_equal_to =>0.01}
  validates :rank , :numericality =>{:greater_than_or_equal_to =>0,:less_than_or_equal_to =>5}
  has_many :foods ,:dependent => :destroy
  has_many :categories ,:dependent => :destroy
  has_many :favorites
  has_many :users , :through => :favorites
  has_many :messages , :dependent => :destroy
  has_many :orders , :dependent => :destroy
  has_many :order_periods, :dependent => :destroy
  accepts_nested_attributes_for :order_periods, allow_destroy: true

  belongs_to :user
  belongs_to :school
  after_save :fresh_store

  def self.find_by_categore(category_name,options = {})
    with_scope :find => options do
      find_all_by_categore(category_name, :order => 'created_at DESC')
    end
  end

  has_attached_file :image_url,
  :styles => {
    :thumb=> "100x100#",
    :small  => "76x76>",
    :nomal  => "220x150>"}

  def self.find_all_category(id)
    a =[]
    Store.find(id).categories.each do |category|
      a << category.name
    end
    a
  end

  #根据获取Store的收入
  def income_by_time(status,start_time,end_time)
    Order.where("store_id = ? and  order_status = ?  and created_at > ? and created_at < ?",id,status,start_time,end_time).map{ |order| order.total_price}.sum
  end

  def image
    image_url.exists?? image_url.url(:small):CONFIG["store_image_miss"]
  end

  #获取收藏的店家
  def self.get_fav_num(store_id)
    fav_store=Favorite.where(:store_id => store_id).select("COUNT(user_id) AS total ")
    fav_store.first.total
  end

  def self.get_store_id_by_user_id(user_id)
    Store.where(:user_id => user_id).first.id
  end

  def get_messages
    Message.where(:store_id=>id).order("id desc")
  end

  def all_comments
    LineItem.joins(:food).where("line_items.content is NOT NULL and foods.store_id =?",id).order("created_at desc")
  end

  def sold_count
    Order.where("store_id = ? and order_status = ? and created_at > ?", id, 3, Time.local(2013,03,01)).size
  end

  def all_complaints
    a=[]
    Order.where("is_complainted = 1 and store_id = ? " ,id).all.each do |order|
      a<< order.my_complaint
    end
    a
  end

  def recent_sales(start_time)
    Order.where("created_at>=? and store_id = ?",start_time,id).size
  end

  def self.new_one_default_store(user_id)
    @store = Store.new
    @store.opentime = Time.now
    @store.closetime = Time.now
    @store.isclose = 0
    @store.rank = 4
    @store.name = "test"
    @store.send_price = 10.0
    @store.image_url_file_name = "test.jpg"
    @store.user_id = user_id
    @store.save
    @store.id
  end

  def self.translate_type_i(status)
    case status
    when "打烊" then 1
    when "开业" then 0
    else 0
    end
  end

  def is_trade?
    is_shop = false
    order_periods.each do |op|
      is_shop = (isclose==0 and (Time.parse op.start_time.to_s)<Time.now and Time.now < (Time.parse op.end_time.to_s))
      break if is_shop
    end
    is_shop
  end

  def translate_type_s
    if isclose == 1
      return "假期歇业中.."
    else
      is_business_to_s
    end
  end

  def is_business
    isclose == 1? false : is_on_time
  end

  def is_business_to_s
    if is_business
      "正在营业中...."
    else
      "打烊中...."
    end
  end

  def sals_counts(time_before=nil,order_status)
    if time_before.nil?
      return   Order.where("store_id =? and order_status = ?",id,order_status).size
    else
      return  Order.where("store_id =? and created_at >=? and order_status = ?",id,time_before,order_status).size
    end

  end

  def find_category_id(name)
    categories.each do |category|
      if category.name == name
        return category.id
      end
    end
  end

  def self.find_market
    Store.where("is_super_market = 1").first
  end

  def open_time
    "#{opentime.strftime '%H:%M'}-#{closetime.strftime '%H:%M'}"
  end

  private

  def isclose_parse
    #self.isclose = STORE_STATUS_ADMIN_HASH[self.isclose]
  end

  def is_on_time
    (get_sec_of_time(opentime.to_datetime) < get_sec_of_time(Time.now)) && (get_sec_of_time(Time.now)<get_sec_of_time(closetime.to_datetime))
  end

  def get_sec_of_time(target_time)
    target_time.hour*3600+target_time.min*60+target_time.sec
  end

  def self.stores_of_a_school(school,refresh=false)
    stores =  Store.where("school_id=?",School.where(:name=>school).first.id).order("sortvalue")
  end

  def self.create_default_store
    Store.transaction do
      Store.create!(
                    :name => "微大学虚拟餐厅",
                    :introduce =>"干净好吃，快捷方便",
                    :address =>"西南石油大学",
                    :opentime => "2012-07-27  7:30:00",
                    :closetime => "2012-07-27  23:00:00",
                    :tags => "直销，免快递费",
                    :categore => "快餐、中餐、西餐",
                    :tel =>"13301631167",
                    :is_super_market =>0,
                    :isclose => 0 ,
                    :send_price => 10,
                    :rank => 4.5,
                    :settledtime => Time.now,
                    :image_url_file_name => "store.jpg",
                    :school => School.last
                    )
    end
  end

  private

  def fresh_store
    School.all.each do |school|
      Store.stores_of_a_school(school.name,true)
    end   
  end
end

app/controllers/admins/stores_controller.rb
#encoding : utf-8
class Admins::StoresController < AdminsController
  def show
    @store= Store.find(params[:id])
  end

  def index
    @default_store = Store.where(:name => "微大学虚拟餐厅").first
    if params["query"] == "" || params["query"].nil?
      @stores = Store.paginate(:page => params[:page], :per_page => 10)
    else
      @stores = Store.where(" name LIKE ?","%#{params["query"]}%").paginate(:page => params[:page], :per_page => 10)
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store= Store.find(params[:id])
    if @store.update_attributes(params[:store])
      flash[:success] = "店家信息更新成功"
      redirect_to "/admins/stores/"+@store.id.to_s
    else
      flash[:error] = "店家信息更新失败"
      redirect_to "/admins/stores/"+@store.id.to_s+"/edit"
    end
  end

  def new
    @store = Store.new
  end

  def create
    if params[:store][:name].nil? || params[:store][:name] == ""
      flash[:error] = "请填写店名才可以新开店"
      redirect_to "/admins/stores/new"
    else
      @store = Store.new
      @default_store = get_defalut_store
      @store.name = params[:store][:name]
      @store.introduce = @default_store.introduce
      @store.address = @default_store.address
      @store.tags = @default_store.tags
      @store.categore = @default_store.categore
      @store.tel = @default_store.tel
      @store.send_price = @default_store.send_price
      @store.rank = @default_store.rank
      @store.opentime = @default_store.opentime
      @store.closetime = @default_store.closetime
      if @store.save!
        flash[:success] = "新开店家成功"
        redirect_to "/admins/stores"
      else
        flash[:error] = "新开店家失败"
        redirect_to "/admins/stores/new"
      end
    end
  end

  private

  def get_defalut_store
    if Store.where(:name => "微大学虚拟餐厅").size == 0
      Store.create_default_store
    else
      Store.where(:name => "微大学虚拟餐厅").first
    end
  end

end

app/helpers/stores_helper.rb
#encoding : utf-8
module StoresHelper
  
  def string_to_a_format_number(s1,n)
      s1 = s1.to_f.round(n) if s1.to_f.to_s ==s1.to_s
      s1
  end
  
  def follow_store(store)
    unless current_user.stores.include?(store)
      raw("<a id='store-fllow' href='javascript:void(0)' onclick='follow_store(#{store.id})'>#{@favoritec_count}</a><p>喜欢就收藏我：</p>")
    else
      raw("<a id='store-unfllow' href='javascript:void(0)' onclick='cancel_follow_store(#{store.id})'>#{@favoritec_count}</a><p>点击取消收藏：</p>")
    end
  end
end

app/views/stores/_comments.html.erb
<div class="main_content_left_result">
			<div class="tab_left tab_out">
					<%=link_to "菜单",store_path(@store)%>
			</div>
			<div class="tab_right tab_on">
        <span>评论</span>
      </div>
			<div class="message_content">
	  <% @store_comments.each do |message|  %>
			<ul class="message">
					<img src="<%=message.user.get_image_url(:thumb)%>" style="border-radius:50px;">
					<span class="username"><%=message.user.username%></span>
					<span class="time"><%=message.created_at.to_s(:db)%></span>
					<p><%=message.comment.blank?? "还不错哦～～":message.comment%><p>
					<%if message.reply%>
					<div style="margin-left:68px;margin-bottom: 12px;">
						 <fieldset>
						 	  <legend>店长回复</legend>
						 		<p><%= message.reply.comment%><p>
						 </fieldset>
					 </div>
					<%end%>
			</ul>
	 <% end %>
	 <%= will_paginate @store_comments %>
	</div>
</div>

<style type="text/css">
	fieldset{
		border:2px groove;
		margin-right: 10px;
		text-align: left;
	}

	legend{
		font-size: 14px;
    color: #3366FF;
}
	}

</style>

app/views/stores/_finance.html.erb
<div class = "main_content_details_table">
  <table width="100%" border="0"  cellpadding="0" cellspacing="0">
    <tr>
    </tr>
    <tr>
      <th>财务结帐区间（半月为单位）</th>
      <th>成功订单销售额</th>
      <th></th>
      <th></th>
    </tr>
    <% @finance.each do |key,value| %>
    <% unless value == 0 %>
    <tr>
      <td><%= key %></td>
      <td><%= value %>元</td>
      <td></td>
      <td></td>
    </tr>
    <% end %>
    <% end %>
  </table>
  <label style="float: right;">销售总额：<%= @sales_sum%>元</label>
  <div style="float: left;">
    <%= form_for @store ,:url=>{:action=>:search_finance}  do |f|%>
    <%= f.text_field :date,:value => Time.now.to_date,:onclick => "WdatePicker()",:size => "10" %>
      <%= f.submit  :查询,:style => "width: 50px;height: 21px;border: none;background-color: #601606;font-size: 12px;color: #FFF;"%>
    <% end %>
  </div>
</div>

app/views/stores/_foods.html.erb
<% if flash[:create_food_info]%>
<script type="text/javascript">
alert('<%= flash[:create_food_info]%>');
</script>
<%end%>

<div class = "main_content_details_table">
	<table width="100%" border="0"  cellpadding="0" cellspacing="0">
		<tr>
			<th>菜名</th>
			<th>价格</th>
			<th>数量</th>
			<th>标签</th>
			<th>热量</th>
			<th>评价</th>
			<th>折扣</th>
			<th>类别</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
		<% @store.categories.each do |category| %>
		<% category.foods.each do |food| %>
		<tr>
			<td><%= food.name %></td>
			<td><%= food.price %></td>
			<td><%= food.sum %></td>
			<td><%= food.tag %></td>
			<td><%= food.energy %></td>
			<td><%= food.rank %></td>
			<td><%= food.sales %></td>
			<td><%= food.category.name%></td>
			<td><a href="javascript:void(0)" onclick="requery_food('#edit_food',<%= food.id%>)">更新</a></td>
			<td><%= link_to '删除', delete_food_stores_path(:food_id => food.id), confirm: '确定删除吗?', method: :delete %></td>
			<td> <% if food.is_recommend == 0%> <a href="javascript:void(0)" onclick="apply_recomment('#recommend_food',<%= food.id%>)">店长推荐</a> <% else %>
			<%= link_to '取消推荐', cancel_ad_stores_path(:food_id => food.id)%>
			<% end %> </td>
		</tr>
		<% end %>
		<% end %>
	</table>
	<br/>
	<a href="javascript:void(0)" onclick="food_edit('#add_food')">添加本店菜品</a>
</div>

<div id="add_food" style="display: none;height:500px;" class="food_form">
	<%= render 'foods/form'%>
</div>
<div id="edit_food" style="display: none;height:500px;" class="food_form">
	<%= render 'foods/edit'%>
</div>
<div id="recommend_food" style="display: none">
	<%= form_for :food,:url=>{:controller=>:foods,:action=>:add_recomment} do |f| %>
	<label>推荐理由：</label>
	<div class="field">
		<%= f.text_area :recomment_description%>
	</div>
	<label>缩略图：</label>
	<div class="field">
		<%= f.file_field :photo %>
		<%= f.hidden_field :id,:id => "recomment_food_id",:name => "recomment_food_id"%>
		<%= f.hidden_field :is_recommend,:value => "1"%>
	</div>
	<div class="actions">
		<%= f.submit  :提交修改%>
	</div>
	<% end %>
</div>

app/views/stores/_topbar.html.erb
<div class="tab tab_<%= @type=="categories"? 'on':'out'%>">
  <%=link_to "菜品分类",edit_stores_path(:type=>"categories")%>
</div>
<div class="tab tab_<%= @type=="foods"? 'on':'out'%>">
  <%=link_to "餐品管理",edit_stores_path(:type=>"foods")%>
</div>
<div class="tab tab_<%= @type=="orders"? 'on':'out'%>">
  <%=link_to "订餐动态",edit_stores_path%>
</div>
<div class="tab tab_<%= @type=="messages"? 'on':'out'%>">
  <%=link_to "客户留言",edit_stores_path(:type=>"messages")%>
</div>
<div class="tab tab_<%= @type=="finance"? 'on':'out'%>">
  <%=link_to "财务统计",edit_stores_path(:type=>"finance")%>
</div>

app/views/stores/destroy.js.erb
$('#store_<%=@store.id%>').hide();

app/views/stores/edit.html.erb
<div class="top">
  <div class="top_vmeal">
    <a href="/"><img src="/images/icon/vmeal.png" /></a><span>店家中心</span>
  </div>
  <div class="top_rightbox">
    <a href="/stores/logout">退出中心</a>
  </div>
</div>
<div class="main">
  <div class="main_content">
    <div class="main_content_left">
      <div class="main_content_left_resinfo">
        <div class="resinfo_left">
          <div class="resinfo_left_line line1">
            <div>
              <%= @store.name%>
            </div>
            <div id="end"></div>
          </div>
          <div class="resinfo_left_line line2">
            地址：<span><%= @store.address%></span>
          </div>
          <div class="resinfo_left_line line3">
            订餐电话：<span><%= @store.tel%></span>
          </div>
          <div class="resinfo_left_line line4">
            营业时间：
            <%@store.order_periods.each do |op|%>
            <%= op.start_time%>-<%= op.end_time%>
            (<%= op.description%>)&nbsp;
            <%end%>
            &nbsp;&nbsp;&nbsp;
            <a href="javascript:void(0)" onclick="show_storeinfo('#order_period')"> <%= "修改" unless @store.order_periods.blank?%></a>&nbsp; <a href="javascript:void(0)" onclick="show_storeinfo('#order_period_new')"> <%= "添加" if @store.order_periods.size<3 %></a>
                                                                                                                                                                                                                              </div>
          <div class="resinfo_left_line line5">
            起送价：<span><%= @store.send_price%></span>元&nbsp;&nbsp;&nbsp;送餐费：
            <% if @store.delivery_charge == 0 %>
            <span style = "color: red;">免费</span>
            <% else %>
            <span><%= @store.delivery_charge%></span>元
            <% end %>
            <% if @store.isclose == 0%>
            <span style="margin-left:25px;color:red;"><b>如果不能营业点击右边按钮自主关店-></b></span>
            <% else %>
            <span style="margin-left:45px;color:red;"><b>点击右边按钮打开店铺正常营业-></b></span>
            <% end %>
          </div>
        </div>
        <div class="resinfo_right">
          <div class="resinfo_right_img">
            <img src="<%= @store.image%>" width="76px" height="76px"/>
          </div>
          <div class="resinfo_right_like">
            <% if @store.isclose == 0%>
            <%= link_to '正在营业' ,close_stores_path%>
            <% else %>
            <%= link_to '点击营业' ,open_stores_path%>
            <% end %>
          </div>
        </div>
        <div class="resinfo_edit">
          <a href="javascript:void(0)" onclick="show_storeinfo('#storeinfo')">编辑信息>></a>
          </div>
        </div>
        <div class="main_content_left_result">
          <%= render 'topbar'%>
          <% if @type == "orders"%>
          <%= render 'orders'%>
          <% elsif @type == "foods" %>
          <%= render 'foods'%>
          <% elsif @type == "messages" %>
          <%= render 'messages'%>
          <% elsif @type == "categories" %>
          <%= render 'categories'%>
          <% elsif @type == "finance"%>
          <%= render 'finance'%>
          <% end %>
        </div>
      </div>
    </div>
    <div class="main_content_right">
      <div class="right main_content_right_tips">
        <span>小提示</span>
        <p>
          <%= @store.public_talk %>
        </p>
        <div class="tips_edit">
          <a href="javascript:void(0)" onclick="show_storeinfo('#store_notice')">编辑提示>></a>
        </div>
      </div>
      <div class="right main_content_right_query">
        <span>查询订单</span>
        <p>
          <%= form_for @store ,:url=>{:action=>:search} do |f|%>
          <%= f.text_field :date,:value => Time.now.to_date,:onclick => "WdatePicker()" %>
          <%= f.submit  :查询%>
          <% end %>
        </p>
      </div>
      <div class="right main_content_right_info">
        <span>订餐统计列表</span>
        <br/>
        <br/>
        <p>
          订单 <span><%= @orders_count%></span>笔  金额<span>&nbsp;<%= @store_total_order_price%></span>元
        </p>
        <p>
          弃单 <span><%= @orders_fail%></span>笔 金额<span>&nbsp;<%= @store_order_fail_price%></span>元
        </p>
        <p>
          成功 <span><%= @orders_count -  @orders_fail %></span>笔 金额<span>&nbsp;<%= @store_total_order_price - @store_order_fail_price %></span>元
        </p>
        <br/>
        <br/>
        <span>餐品统计排行</span>
        <br/>
        <br/>
        <% @hot_foods.each_with_index do | food , index | %>
        <p style="margin-bottom: 5px">
          <span><%= index + 1%>.</span><%= food[0]%> <span><%= food[1]%>份</span>
        </p>
        <% end %>
        <br/>
        <br/>
      </div>
    </div>
  </div>
</div>

<div id="storeinfo" style="display: none">
  <%= form_for @store,:url=>{:action=>:update} do |f| %>
  <div class="field">
    <%= f.label :店铺名称 %>
    <%= f.text_field :name ,:size=>30%>
  </div>
  <div class="field">
    <%= f.label :外卖费用 %>
    <%= f.text_field :delivery_charge %>
  </div>
  <div class="field">
    <%= f.label :主营业务 %>
    <%= f.text_field :main_sales %>
  </div>
  <div class="field">
    <%= f.label :店家地址 %>
    <%= f.text_field :address ,:size=>40%>
  </div>
  <div class="field">
    <%= f.label :起送价 %>&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.text_field :send_price ,:size=>10%>
  </div>
  <div class="field">
    <%= f.label :联系电话 %>
    <%= f.text_field :tel ,:size=>16%>
  </div>
  <div class="field">
    <%= f.label :店家缩略图%>
    <%= f.file_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit  :提交修改%>
  </div>
  <% end %>
</div>

<div id="store_notice" style="display: none">
  <%= form_for @store,:url=>{:action=>:update} do |f| %>
  <div class="field">
    <%= f.label :公告 %>
    <br />
    <%= f.text_area :public_talk%>
  </div>
  <div class="actions">
    <%= f.submit  :提交修改%>
  </div>
  <% end %>
</div>

<div id="order_period" style="display: none">
  <%= form_for @store,:url=>{:action=>:order_periods} do |f| %>
  <h3>时间段设置</h3>
  <div id='order_periods' class="order_periods">
    <%= f.fields_for :order_periods do |builder| %>
    <%= render "order_period", f:builder%>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit  :提交修改,:class=>"command"%>
  </div>
  <% end %>
</div>

<div id="order_period_new" style="display: none">
  <%= form_for :store,:url=>{:action=>:order_periods} do |f| %>
  <div id='order_periods' class="order_periods">
    <%= f.text_field :task  , :class=> "main_content_input" , :type => "hidden" ,:value=>"new" %>
    <%= f.fields_for :order_periods do |builder| %>
    <%= render "order_period", f:builder%>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit  :提交修改,:class=>"command"%>
  </div>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
  $("#store_date").focusin(function() {
  if ($(this).attr("value") == "点击选择日期") {
  $("#store_date").attr("value", "");
  }
  });
  $("#store_date").focusout(function(){
  if($(this).attr("value")==""){
  $("#store_date").attr("value","点击选择日期");
  }
  });
  });
</script>