config/routes.rb
Vmeal::Application.routes.draw do

  root :to => "home#index"

  get "test/index"

  get "qingans/index"

  get "qingan/index"

  resources :score_histories, :only=>[:index,:new,:create]
  resources :activities, :only=>[:index,:show]
  namespace :admins do
    resources :stores, :store_users, :orders, :emails,:notices,:phone_lists,:schools
    resources :users do
      collection do
        post "query" => "users#query"
        get "export" => "users#export", :as=>"export"
        post "do_export"=>"users#do_export"
      end
      get "history/(:id)" => "users#history" ,:as=>"history"
      get "is_locked/(:id)" => "users#is_locked" ,:as=>"is_locked"
    end
    resources :ads do
      collection do
        post "query" => "ads#query"
      end
      get "is_locked" => "ads#is_locked" ,:as=>"is_locked"
    end
    resources :station_mails do
      collection do
        get "send_mail"
        get "new_user"
      end
    end

    resources :messages do
      collection do
        get "is_locked/(:type)/(:id)" =>"messages#is_locked"
        post "query" => "messages#query"
      end
    end
    resources :vmails do
        collection do
            get "sent_now"=>"vmails#sent_now"
        end
     end
    resources :activities do
        collection do
            get "kaijiang/(:id)" =>"activities#kaijiang"
        end
    end

  end

  resources :admins  do
    collection do
      get "finance"
      get "login"=>"admins#login"
      get "logout"=>"admins#logout"
    end
  end

  resources :station_mails do
    collection do
      get 'send_mail'
    end
  end

  get "notices/:id"=>"notices#show"


  resources :integral_consumer_records do
    collection do
      get "change_status"
    end
  end

  resources :logistics do
    collection do
      get "center"
      get "orderinfo"
      get "login"
      get "history"
      post "islogin"
      get "changeorder"
      get "filedorder"
    end
  end

  resources :order_manager do
    collection do
      get "midify_status"
      get "set_be_watered"
      post "search"
      get "set_user_is_ok"
      get "destroy1"
      get 'has_order'
      get 'has_store_order'
    end
  end

  resources :qingans

  get 'pc/i_want'

  resources :applications do
    collection do
      get "list_all_my_applications"
      get "sh"
      get 'succuss'
      get 'failure'
    end
  end

  resources :fs_manager do
    collection do
      get "change_status"
      get "destroy1"
    end
  end

  get "season_foods/:id/show" =>"season_foods#show"

  resources :super_market do
    member do
      get 'show'
    end
  end

  post "/complaints/do_complaint" =>"complaints#do_complaint"

  resources :messages

  resources :send_addresses

  resources :home ,:only =>[:index] do
    collection do
      get "show_stores"
      get 'qingan' => "home#qingan", :as => :qingan
      post 'signup'
    end
  end
  get "/sina" => "home#sina"

  get "about_us/(:type)" => "about_us#about_link", :as => :about_us

  resources :season_foods

  resources :sto_categories
  resources :send_addresses

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :sessions => "sessions"
  }

  devise_scope :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    collection do
      get 'qqlogin'
      get 'sina_login'
      get 'get_user_qq_info'
      get 'center'
      get 'destory_favorite_food'
      get 'destory_favorite_store'
      get 'destory_user_address'
      get 'left'
      get 'person_center'
      get 'person_center_avatar'
      get 'person_center_order_history'
      get 'person_center_order_uncomment'
      get 'person_center_fav_food'
      get 'person_center_integral'
      get 'person_center_comment'
      get 'person_center_message'
      get 'person_center_fav_store'
      get 'person_center_address'
      get 'person_center_address_new'
      get 'person_center_password'
      get 'destory_favorite_food'
      get 'destory_favorite_store'
      get 'destory_address/:address_id'=>"users#destory_address",:as=>:destory_address
      get 'register_email'
      get 'set_default_address'
      get 'person_center_info'
      get 'bill'
      get 'user_complaints'
      get 'do_complaint'
      get 'do_one_complaint'
      get 'send_addresses_new'
      get 'do_com' =>'users#do_one_order_comment'
      get 'change_line_item_quantity'
      post 'create_user_weibo'
      post 'is_login_in_uid'
      post 'save_com' =>'users#save_order_comment'
      get 'eat_one'
      get 'resend_email'
      get 'send_email'
      get 'bill_empty'
      get 'integral_bill'
      get 'create_exchange_good'
      get 'change_exchange_good_number'
      get 'integral_bill_empty'
      get 'person_center_integral_history'
      get 'home'=>"users#personal_basic"
      get 'address'=>"users#personal_address"
      get 'collects'=>"users#personal_collect",:as=>:collects
      get 'mails/:status'=>"users#personal_mail",:as=>:mails
      get 'orders/:status'=>"users#personal_order",:as=>:orders
      get 'account'=>"users#personal_account"
      get 'create_message'
      get 'read_mail'
      get 'delete_mail'
      get 'stores_manage'
      get 'drop_order'
      get 'score_histories/(:type)'=>"users#score_histories",:as=>:score_histories,:constraints => { :type => /add|sub|/ }
      get 'welfare/(:type)'=>"users#welfare"
      post 'welfare/address_create' =>"users#good_address_create"
      get "qiandao"=>"users#qiandao"
    end
  end

  resources :orders ,:only=>[:new,:create,:destroy,:show]

  resources :line_items ,:only=>:create do
    collection do
      post 'modify/:task'=>"line_items#modify",:as=>:modify
    end
  end

  resources :orders do
    collection do
      get 'apply_fail_order'
      get 'do_fail_order'
      get 'recover_order'
    end
  end

  resources :foods do
    collection do
      get "add_favorite_foods"
      get "search"
      get 'add_recomment'
    end
  end

  resources :categories do
    resources :foods
  end

  resources :stores  ,:only=>[:show] do
    collection do
      get "add_fav_store"
      get 'cancel_fav_store'
      get 'edit/(:type)'=>"stores#edit",:as=>:edit
      get 'open'
      get 'close'
      get 'delete_food'
      get 'login'
      get 'logout'
      get 'order_details'
      get 'delete_category'
      get 'cancel_ad'
      get 'order_success'
      get 'has_new_order/(:store_id)/(:max_order_id)'=>"stores#has_new_order"
    end
  end

  resources :reply, :only=>[:show,:create]

  get "stores/:id/delete"=>"stores#destroy"

  post "serarch"=>"foods#serarch"

  post "otherlogin" => "users#otherlogin"

  get "stores/:id/delete"=>"stores#destroy"

  post "carts/action/:type" => "carts#action"

  get 'cj/:type', to: "activities#index", constraints: { type:  /coming|history/ }
  get 'cj/:id', to: "activities#show", constraints: { :id => /\d+/ }
  resources :score_histories
  get 'cj/confirm_order'=>"score_histories#new"
  get 'cj/error'=>"score_histories#error"
  get 'faq/jf_rule' => "faq#jf_rule"
  get 'locate' => 'home#location'
  get 'choose/(:id)' => 'home#set_location'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    unless cookies[:school]
      redirect_to '/locate'
    else
      @stores = Store.stores_of_a_school(cookies[:school])
      @phone_stores = @stores.select{|store| store.isphone == 2}
      @net_stores = @stores - @phone_stores
      @hot_foods = Food.hot_foods(cookies[:school])
      @users_count = User.numbers(refresh = true)
      @food_ads = Ads.all_ads(cookies[:school],2)
      @jd_ads = Ads.all_ads(cookies[:school],1)
      @notices = Notice.order("updated_at desc").limit(5)
      login_by_qq unless params[:code].nil?
    end
  end

  def sina
    unless params[:code].nil?
      client = WeiboOAuth2::Client.new
      access_token = client.auth_code.get_token(params[:code].to_s)
      unless access_token.nil?
        session[:uid] = access_token.params["uid"]
        session[:access_token] = access_token.token
        session[:expires_at] = access_token.expires_at
        @user = User.find_by_uid(session[:uid].to_s)
        user_infor = client.users.show_by_uid(session[:uid].to_i)
        if @user
          @user.image_url_file_name = user_infor.profile_image_url
          @user.username = user_infor.name
          @user.save
          sign_in(@user)
        else
          session[:need_binding] = true
          session[:login_by_other] = {:user_type =>"sina",:uid =>session[:uid],:username =>user_infor.name,:image_url => user_infor.profile_image_url}
        end
      end
    end
    redirect_to root_path
  end

  def show_stores
    @sto_categories = StoCategory.all
  end

  def location
  end

  def qingan
   @qingan =  Qingan.new
    render :layout => "devise"
  end

  def signup
    @qingan = Qingan.new(params[:qingan])
    if @qingan.save
      flash[:qingan] =  "恭喜你报名成功，我们会尽快联系您！"
      redirect_to qingan_home_index_path
    else
      flash[:qingan] =  "亲，请填写正确的信息再报名！"
      redirect_to qingan_home_index_path
    end
  end

  def set_location
      school = School.find(params[:id])
      if school
         set_locate_school(school.name)
         redirect_to root_path
      else
         redirect_to '/locate'
      end
  end

private
  def login_by_qq
    begin
      httpstat=request.env['HTTP_CONNECTION']
      qq = Qq.new
      token = qq.get_token(params[:code],httpstat)
      qq_user_infor = qq.get_user_info(token)
      if @user = User.find_by_uid(qq_user_infor["nickname"].to_s + qq_user_infor["figureurl"].to_s)
        sign_in @user
      else
        session[:need_binding] = true
        session[:login_by_other] = {:user_type =>"qq",:uid =>qq_user_infor["nickname"].to_s + qq_user_infor["figureurl"].to_s,:username =>qq_user_infor["nickname"],:image_url =>qq_user_infor["figureurl_2"]}
        # qq.add_share(token,"微大学你身边的外卖专家","http://www.weidaxue.me","我正在使用微大学订餐平台",'“微大学”结合B2B,B2C网络订餐的概念，为餐厅提供一体化运营的解决方案，致力于推进餐饮行业信息化的发展进程 http://weidaxue.me 。','http://tp3.sinaimg.cn/2969909902/180/22821137424/1',"微大学","http://www.weidaxue.me")
      end
    rescue Exception =>e
      redirect_to root_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  
 def get_store_open_time(store)
    "#{store.opentime.strftime '%H:%M'}-#{store.closetime.strftime '%H:%M'}"
 end

 def format_notice(notices)
 	raw notices.map{|notice|"\"<a href='/notices/#{notice.id}'>#{notice.title}</a>\""}.join(",")
 end
end

app/views/home/_food_ads.html.erb
<div class="ordering_center_left_recommend">
  <%@food_ads.first(3).each_with_index do |ad,index| %>
  <div class="ordering_center_left_recbox" 
       <% if index.odd?%>
       style="padding-left:26px; padding-right:26px;position: relative;"
       <%else%>
       style="position: relative;"
       <% end %>
       >
    <a href="<%=ad.link_to%>" title="<%=ad.title%>">
      <img src="<%=ad.img_path%>" width="190" height="190" />
    </a>
    <div class="recbox_tips"
      <% if index.odd?%>
       style="margin-left:26px; margin-right:26px;"
       <%end%>
      >
      <div class="ordering_center_left_restaurant_line3"><%=ad.store.nil? ? 0 : ad.store.sold_count%></div>
      <a class="recbox_tips_name" href="/stores/<%=ad.store_id%>"><%=ad.title%></a>
      <div id="dis_content">
        <p class="recbox_tips_des"><a href="<%=ad.link_to%>"><%=ad.describe.nil? ? '   ' : ad.describe%></a></p>
        <a class="recbox_tips_res_link" href="/stores/<%=ad.store_id%>"><%=ad.store.nil? ? '微大学餐厅' : ad.store.name%></a>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/home/_hot_foods.html.erb
<% cache "hot_foods_#{cookies[:school]}", :expires_in => 2.hour do %>
<div class="ordering_center_right_ranking">
<div class="ordering_center_right_ranking_title">
<div class="ordering_center_right_ranking_title_pic"><img src="images/icon/rank.png" width="16" height="16" /></div>
<div class="ordering_center_right_ranking_title_text">热卖排行</div>
</div>

<div class="ordering_center_right_ranking_content">

<%@hot_foods.each_with_index do |food,index|%>
<div class="ordering_center_right_ranking_list">
<div class="ordering_center_right_ranking_num"><%=index+1%>.</div>
<div class="ordering_center_right_ranking_text">
<div class="ordering_center_right_ranking_name"
<%if food.store.is_trade?%> 
   onclick="do_eat_post_and_redirect('<%=food.store.id %>','<%=food.store.name%>','<%= food.id%>','<%= food.name%>','<%= food.price%>');"
<%else%>
   onclick="only_redirect_to('<%=food.store.id%>');"
<%end%> >
<a style="cursor:pointer;"><%=food.name%></a>
</div>
<div class="ordering_center_right_ranking_pic"
<%if food.store.is_trade?%> 
   onclick="do_eat_post_and_redirect('<%=food.store.id %>','<%=food.store.name%>','<%= food.id%>','<%= food.name%>','<%= food.price%>');"
<%else%>
   onclick="only_redirect_to('<%=food.store.id%>');"
<%end%>>
<img src="/images/icon/buy.png" width="16" height="16" /></div>
<div class="ordering_center_right_ranking_sales">&nbsp;<%=food.sales_count%></div>
</div>
</div>

<%end%>

</div>
</div>
</div>
<%end%>

app/views/home/_login.html.erb
<div class="ordering_mainfocus_right">
	<% if user_signed_in? %>
    <div align="center" class="ordering_mainfocus_right">
    <div class="ordering_mainfocus_right_loginimg"> <a href="/users/home"><img src="<%=current_user.get_image_url("thumb")%>" id="userimg" width="70" height="70" border="0"></a><div style="color: #7D1F0A;">
    	(<span id="my_score_home"><%= current_user.integral%></span>积分)
    </div>
  </div>
    <div class="ordering_mainfocus_right_username"> <a href="/users/home" class="ordering_mainfocus_right_login_name"><%= current_user.username%></a></div>
    <div class="ordering_mainfocus_right_others">
    <a href="/logout">注销登录</a>&nbsp;
    <a href="/users/orders/building">我的订单</a>&nbsp;
    <a href="/cj">我要抽奖</a>&nbsp;
    
</div>
      </div>
	<% else %>
	<div class="ordering_mainfocus_right_ask">
		已经有<font color="#7D1F0A"><%=@users_count%></font>吃货吃爽，你也参与？
	</div>
	<div class="ordering_mainfocus_right_login">
		<input type="button" onclick="dk()" class = "ordering_mainfocus_right_button" value="登录">
	</div>

	<div class="ordering_mainfocus_right_none">
		尚无账号？<a href="/users/sign_up">点击注册</a>
	</div>
	<div class="ordering_mainfocus_right_otherlogin">
		<div class="ordering_mainfocus_right_otherbox qqlogin">
			<div class="ordering_mainfocus_right_link">
				<a href="/users/qqlogin">QQ登录</a>
			</div>
		</div>
		<div class="ordering_mainfocus_right_otherbox bloglogin">
			<div class="ordering_mainfocus_right_link">
				<a href="/users/sina_login">微博登录</a>
			</div>
		</div>
	</div>
	<% end %>
</div>
</div>

<%= render :partial =>"shared/login_form" ,:locals=>{:type=>1}%>

app/views/home/_other_login.html.erb
<%if session[:need_binding]%>
	<%unless current_user%>
		<script type="text/javascript">
			$(document).ready(function() {
				$.layer({
		    		type : 1,
		    		title : ['',false],
		    		closeBtn : ['0',true],
		    		border : [10 , 0.3 , '#000', true],
		    		area : ['auto','auto'],
		    		page : {dom : '#otherlogin'}
				});
			});

			function login_other (arge) {
				var url = "/otherlogin";
				if (arge==0){
					url = url + "?type=0"
				};
				$.ajax({
							type : "POST",
							url : url,
							beforeSend : function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));},
							data : {email : $("#email").attr("value"),password:$("#password").attr("value")},
							dataType : "json",
							success : function(data) {
								if(data.status == "ok")
								{
									window.location = "/";
								}else
								{
									$("#msg").html(data.error_msg);
								}
							}
				});
			}
		</script>
	<%end%>
<%end%>

app/views/home/qingan.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>青安驾校欢迎您！</title>
    <link href="/css/qingan.css" type="text/css" rel="stylesheet" />
  </head>

  <body>
    <div class="base">
      <div class="main">
        <div class="top">
          <img src="/css/images/banner_a.png"  />
        </div>

        <div class="info">
          <div class="info_box">
            <img src="/css/images/kaochang1.jpg"/>
            <span>申领条件</span>
            <div>
              初次此申领的车型为C1、B2、E<br />
              申请增驾B1的，需取得C1、C2三年以上或者取得B2一年以上<br />
              申请增驾A1的，需取得B1，B2五年以上或者取得A2两年以上
            </div>
          </div>


          <div class="info_box">
            <img src="/css/images/kaochang2.jpg"/>
            <span>报名资料</span>
            <div>
              初次申领的学员需交验身份证，外地户口须办理暂住证，并提供复印件各2份，白底彩色相片1寸12张（免冠，不戴眼镜，不穿制服）<br />
              申请增驾的学员需交验身份证，并提供身份证复印件3份，现有驾驶证复印件1份，白底彩色相片1寸12张（免冠，不戴眼镜，不穿制服）
            </div>
          </div>


          <div class="info_box">
            <img src="/css/images/kaochang3.jpg"/>
            <span>年龄及身高</span>
            <div>
              小型汽车C1：
              18—70周岁 &nbsp;150cm以上<br />
              大型货车B2：
              21—50周岁 &nbsp;155cm以上<br />
              大型客车A1：
              26—50周岁 &nbsp;155cm以上<br />
              摩托车E：
              18—60周岁 &nbsp;无上限<br />

            </div>
          </div>

        </div>

        <div class="process">
          <img src="/css/images/process.png" width="960" height="90" /> </div>



        <div class="apply">
          <div class="apply_left">
            <div>
              青&nbsp;安&nbsp;驾&nbsp;校<br />
              火&nbsp;热&nbsp;报&nbsp;名

            </div>

          </div>
          <div class="apply_right_base">
            <div class="apply_right">
              <div class="apply_center">
                <div>在下面填写报名信息，我们将以最快的速度联系您！</div>
                <%= form_for @qingan,:url =>signup_home_index_path  do |f|%>
                <div><span>姓名</span><%= f.text_field :name %></div>
                <div><span>联系电话</span><%= f.text_field :telephone%></div>
                <%= f.submit '立即报名',:class => "button"%>
                <% end %>
              </div>

              <div class="apply_center">
                <div>您也可以主动联系我们哦！</div>
                <div><span>店铺地址:</span><p>成都市新都区正因街10号。</p></div>
                <div><span>联系电话:</span><p>15114020808（谭教练）<br />
                    15388198689 <br />
                    13541236262 （王教练）</p></div>
              </div>


              <div class="apply_img">
                <img src="/css/images/qa.jpg" /> </div>

            </div>
          </div>
        </div>





        <div class="promise">
          <div class="promise_main">
            <span>郑&nbsp;重&nbsp;承&nbsp;诺</span>
            <div>
              1、以最优的服务质量，最好的服务态度，接待每一位学员。<br />
              2、最低的教学价格，中途不增收任何其它费用。最快的时间报考考试，出驾照。<br />
              3、团报（5人以上）享受团队价格。
            </div>
          </div>


          <div style="padding-left:30px; float:left; width:465px; height:auto;">

            <div class="promise_main">
              <span>敬&nbsp;告</span>
              <div>
                学习有效期为三年（以报名之日起）过期无效，已交的所有费用不予退还，中途退学的已向车管部门办理手续的所有费用由车管部门处理，所学的学时按平时80元/小时，周末100元/小时收取。
              </div>
            </div>
          </div>

        </div>





      </div>
    </div>

    <div class="bottom">
      友情链接:
      <a href="#">青安驾校官网</a>
      <a href="#">驾考一点通</a>
      <a href="#">微大学订餐平台</a>
      <a href="#">西南石油大学</a>
      <a href="#">油吧</a>
      <a href="#">四川音乐学院</a>
      <a href="#">成都医学院</a>
    </div>
    <div class="bottom_line"></div>
  </body>
</html>

<% if flash[:qingan]%>
<script type="text/javascript">
  alert('<%= flash[:qingan]%>');
</script>
<%end%>

app/views/home/show_stores.html.erb
<link href="/css/ordering_restaurants.css" rel="stylesheet" type="text/css" />

<div id="ordering_restaurants_contentbase">
	<div id="ordering_restaurants_content">
		<input id="menu_type" type="hidden" value="store">
		<div class="ordering_restaurants_category">
			<table width="958" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<td width="60" align="right" valign="middle">类别：</td>
					<td width="898" align="left" valign="middle">
					<input type="hidden" id="item" value="全部"/>
					<input id="item全部" type="button" class="ordering_restaurants_category_button_select" onclick="selectitem('全部');jQuery(this).removeClass().addClass('ordering_restaurants_category_button_select');" value="全部" />
					<%StoCategory.find_all_story_category.each do |name|%>
					<input id="item<%= name%>" type="button" class="ordering_restaurants_category_button" onclick="selectitem('<%= name%>');jQuery(this).removeClass().addClass('ordering_restaurants_category_button_select')" value="<%= name%>" />
					<%end%> </td>
				</tr>
				<tr>
					<td align="right" valign="middle">特色：</td>
					<td align="left" valign="middle">
					<input id="tag全部" type="button" onclick="selecttag('全部')" class="ordering_restaurants_category_button_select" value="全部" />
					<%Store::STORE_TAGES.each do |tag|%>
					<input id="tag<%= tag%>" type="button" class="ordering_restaurants_category_button" onclick="selecttag('<%= tag%>')" value="<%= tag%>" />
					<%end%></td>
				</tr>
				<tr>
					<td align="right" valign="middle">状态：</td>
					<td align="left" valign="middle">
					<input type="button" class="ordering_restaurants_category_button_select" value="全部" />
					<input type="button" class="ordering_restaurants_category_button" value="营业中" />
					<input type="button" class="ordering_restaurants_category_button" value="打烊中" />
					</td>
				</tr>
			</table>

		</div>
		
		<script>
			function selectitem (arge) {
				flage=true;
			  if(arge=="全部"){
			  	<%@sto_categories.each do |store_category|%>
			  		
			  		if(!$("#type<%= store_category.name%>").find(".ordering_restaurants_shoplist").find('.ordering_restaurants_shopborder').is(":hidden")&&flage){
			  			flage=false;
			  		}
			  		if(!flage){
			  			$("#type<%= store_category.name%>").show();	
			  		}else{
			  			$("#type<%= store_category.name%>").hide();
			  		}
			  		$("#item").attr("value",arge);
			  		jQuery($("#item<%= store_category.name%>")).removeClass().addClass('ordering_restaurants_category_button');
			  	<%end%>
			  }else{
			  <%@sto_categories.each do |store_category|%>
			  	if(arge=="<%= store_category.name%>"){
			  		$("#type"+arge).show();
			  		$("#item").attr("value",arge);
			  		if(!$("#type<%= store_category.name%>").find(".ordering_restaurants_shoplist").find('.ordering_restaurants_shopborder').is(":hidden")&&flage){
			  			flage=false;
			  		}
			  		if(!flage){
			  			$("#type<%= store_category.name%>").show();	
			  		}else{
			  			$("#type<%= store_category.name%>").hide();
			  		}
			  		jQuery($("#item"+arge)).removeClass().addClass('ordering_restaurants_category_button_select');
			  		jQuery($("#item全部")).removeClass().addClass('ordering_restaurants_category_button');
			  	}else{
			  		<%@sto_categories.each do |store_category1|%>			  		
			  			<%if store_category.name!=store_category1.name%>
			  				$("#type<%= store_category.name%>").hide();	
			  				jQuery($("#item<%= store_category.name%>")).removeClass().addClass('ordering_restaurants_category_button');
			  				jQuery($("#item全部")).removeClass().addClass('ordering_restaurants_category_button');		  			
			  			<%end%>
			  	<%end%>
			  	}
			  <%end%>
			  }
			};
			
			function selecttag (arge) {
				if(arge=="全部"){
			   <%Store::STORE_TAGES.each do |tag|%>			  		
			  		var content="span:contains('";
					content=content+"<%=tag%>";
					content=content+"')";
					$(content).parent().parent().show();
			  		jQuery($("#tag<%= tag%>")).removeClass().addClass('ordering_restaurants_category_button');
			  		jQuery($("#tag全部")).removeClass().addClass('ordering_restaurants_category_button_select');
			  	<%end%>
			  }else{			  	
			  	var flage=true;
			  	var flag=true;
			  	<%Store::STORE_TAGES.each do |tag|%> 
			  			jQuery($("#tag<%= tag%>")).removeClass().addClass('ordering_restaurants_category_button');
			  			jQuery($("#tag全部")).removeClass().addClass('ordering_restaurants_category_button');
			  			var content="span:contains('";
						content=content+"<%=tag%>";
						content=content+"')";
						$(content).parent().parent().hide();
						$(content).parent().parent().parent().parent().hide();
			  	<%end%>
			  	jQuery($("#tag全部")).removeClass().addClass('ordering_restaurants_category_button');
			  	jQuery($("#tag"+arge)).removeClass().addClass('ordering_restaurants_category_button_select');
			  	var content="span:contains('";
				content=content+arge;
				content=content+"')";
				$(content).parent().parent().parent().parent().show();
				$(content).parent().parent().show();				
				selectitem($("#item").attr("value"));
			  };
			};
			
		</script>
		
		
		
		
		<%@numbertype=0%>
		<%@sto_categories.each do |store_category|%>
		<%@numbertype=@numbertype+1%>
		<%@stores = store_category.find_all_stores%>
		<%if @stores.size>0%>
		<div id="type<%=store_category.name%>">
		<div class="ordering_restaurants_tittle">
			<%= store_category.name%>
		</div>
		<div class="ordering_restaurants_shoplist_border">
		<div class="ordering_restaurants_shoplist">
			<%@stores.each do |store|%>
			<div class="ordering_restaurants_shopborder">
				<div class="ordering_restaurants_shop_top">
					<div class="ordering_restaurants_shop_left">
						<a href="/stores/<%= store.id%>"><img src="<%= store.get_image_url%>" width="60" height="60"/></a>
					</div>
					<div class="ordering_restaurants_shop_right">
						<div class="ordering_restaurants_shop_name">
							<%= link_to store.name , store_path(store)%>
						</div>
						<div class="ordering_restaurants_shop_label">
							<%= store.main_sales%>
						</div>
						<div class="ordering_restaurants_shop_label">
								<div class="show_start">
								<img src="/images/star.png" id="store_show_<%= store.id%>" onload="javascript:show_start('store_show_<%= store.id%>',<%= store.rank%>)">
							   </div>
						</div>
					</div>

				</div>
				<div class="ordering_restaurants_shop_status">
					<div class="ordering_restaurants_shop_status_left">
						<%= store.sent_time%>分钟
					</div>
					<div class="ordering_restaurants_shop_status_right">
						<%= link_to "收藏", add_fav_store_stores_path(:store_id => store.id)%>
					</div>
				</div>
				<div class="ordering_restaurants_shop_status">
					<span><%= store.tags%><span>
				</div>
			</div>
			<%end%>
		</div>
		</div>
</div>
<%end%>
		<%end%>
	</div>
</div>