config/routes.rb
Vmeal::Application.routes.draw do

  root :to => "home#index"

  get "test/index"

  get "qingans/index"

  get "qingan/index"

  resources :score_histories, :only=>[:index,:new,:create]
  resources :activities, :only=>[:index,:show]
  namespace :admins do
    resources :stores, :store_users, :orders, :emails,:notices,:phone_lists,:schools
    resources :users do
      collection do
        post "query" => "users#query"
        get "export" => "users#export", :as=>"export"
        post "do_export"=>"users#do_export"
      end
      get "history/(:id)" => "users#history" ,:as=>"history"
      get "is_locked/(:id)" => "users#is_locked" ,:as=>"is_locked"
    end
    resources :ads do
      collection do
        post "query" => "ads#query"
      end
      get "is_locked" => "ads#is_locked" ,:as=>"is_locked"
    end
    resources :station_mails do
      collection do
        get "send_mail"
        get "new_user"
      end
    end

    resources :messages do
      collection do
        get "is_locked/(:type)/(:id)" =>"messages#is_locked"
        post "query" => "messages#query"
      end
    end
    resources :vmails do
        collection do
            get "sent_now"=>"vmails#sent_now"
        end
     end
    resources :activities do
        collection do
            get "kaijiang/(:id)" =>"activities#kaijiang"
        end
    end

  end

  resources :admins  do
    collection do
      get "finance"
      get "login"=>"admins#login"
      get "logout"=>"admins#logout"
    end
  end

  resources :station_mails do
    collection do
      get 'send_mail'
    end
  end

  get "notices/:id"=>"notices#show"


  resources :integral_consumer_records do
    collection do
      get "change_status"
    end
  end

  resources :logistics do
    collection do
      get "center"
      get "orderinfo"
      get "login"
      get "history"
      post "islogin"
      get "changeorder"
      get "filedorder"
    end
  end

  resources :order_manager do
    collection do
      get "midify_status"
      get "set_be_watered"
      post "search"
      get "set_user_is_ok"
      get "destroy1"
      get 'has_order'
      get 'has_store_order'
    end
  end

  resources :qingans

  get 'pc/i_want'

  resources :applications do
    collection do
      get "list_all_my_applications"
      get "sh"
      get 'succuss'
      get 'failure'
    end
  end

  resources :fs_manager do
    collection do
      get "change_status"
      get "destroy1"
    end
  end

  get "season_foods/:id/show" =>"season_foods#show"

  resources :super_market do
    member do
      get 'show'
    end
  end

  post "/complaints/do_complaint" =>"complaints#do_complaint"

  resources :messages

  resources :send_addresses

  resources :home ,:only =>[:index] do
    collection do
      get "show_stores"
      get 'qingan' => "home#qingan", :as => :qingan
      post 'signup'
    end
  end
  get "/sina" => "home#sina"

  get "about_us/(:type)" => "about_us#about_link", :as => :about_us

  resources :season_foods

  resources :sto_categories
  resources :send_addresses

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :sessions => "sessions"
  }

  devise_scope :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    collection do
      get 'qqlogin'
      get 'sina_login'
      get 'get_user_qq_info'
      get 'center'
      get 'destory_favorite_food'
      get 'destory_favorite_store'
      get 'destory_user_address'
      get 'left'
      get 'person_center'
      get 'person_center_avatar'
      get 'person_center_order_history'
      get 'person_center_order_uncomment'
      get 'person_center_fav_food'
      get 'person_center_integral'
      get 'person_center_comment'
      get 'person_center_message'
      get 'person_center_fav_store'
      get 'person_center_address'
      get 'person_center_address_new'
      get 'person_center_password'
      get 'destory_favorite_food'
      get 'destory_favorite_store'
      get 'destory_address/:address_id'=>"users#destory_address",:as=>:destory_address
      get 'register_email'
      get 'set_default_address'
      get 'person_center_info'
      get 'bill'
      get 'user_complaints'
      get 'do_complaint'
      get 'do_one_complaint'
      get 'send_addresses_new'
      get 'do_com' =>'users#do_one_order_comment'
      get 'change_line_item_quantity'
      post 'create_user_weibo'
      post 'is_login_in_uid'
      post 'save_com' =>'users#save_order_comment'
      get 'eat_one'
      get 'resend_email'
      get 'send_email'
      get 'bill_empty'
      get 'integral_bill'
      get 'create_exchange_good'
      get 'change_exchange_good_number'
      get 'integral_bill_empty'
      get 'person_center_integral_history'
      get 'home'=>"users#personal_basic"
      get 'address'=>"users#personal_address"
      get 'collects'=>"users#personal_collect",:as=>:collects
      get 'mails/:status'=>"users#personal_mail",:as=>:mails
      get 'orders/:status'=>"users#personal_order",:as=>:orders
      get 'account'=>"users#personal_account"
      get 'create_message'
      get 'read_mail'
      get 'delete_mail'
      get 'stores_manage'
      get 'drop_order'
      get 'score_histories/(:type)'=>"users#score_histories",:as=>:score_histories,:constraints => { :type => /add|sub|/ }
      get 'welfare/(:type)'=>"users#welfare"
      post 'welfare/address_create' =>"users#good_address_create"
      get "qiandao"=>"users#qiandao"
    end
  end

  resources :orders ,:only=>[:new,:create,:destroy,:show]

  resources :line_items ,:only=>:create do
    collection do
      post 'modify/:task'=>"line_items#modify",:as=>:modify
    end
  end

  resources :orders do
    collection do
      get 'apply_fail_order'
      get 'do_fail_order'
      get 'recover_order'
    end
  end

  resources :foods do
    collection do
      get "add_favorite_foods"
      get "search"
      get 'add_recomment'
    end
  end

  resources :categories do
    resources :foods
  end

  resources :stores  ,:only=>[:show] do
    collection do
      get "add_fav_store"
      get 'cancel_fav_store'
      get 'edit/(:type)'=>"stores#edit",:as=>:edit
      get 'open'
      get 'close'
      get 'delete_food'
      get 'login'
      get 'logout'
      get 'order_details'
      get 'delete_category'
      get 'cancel_ad'
      get 'order_success'
      get 'has_new_order/(:store_id)/(:max_order_id)'=>"stores#has_new_order"
    end
  end

  resources :reply, :only=>[:show,:create]

  get "stores/:id/delete"=>"stores#destroy"

  post "serarch"=>"foods#serarch"

  post "otherlogin" => "users#otherlogin"

  get "stores/:id/delete"=>"stores#destroy"

  post "carts/action/:type" => "carts#action"

  get 'cj/:type', to: "activities#index", constraints: { type:  /coming|history/ }
  get 'cj/:id', to: "activities#show", constraints: { :id => /\d+/ }
  resources :score_histories
  get 'cj/confirm_order'=>"score_histories#new"
  get 'cj/error'=>"score_histories#error"
  get 'faq/jf_rule' => "faq#jf_rule"
  get 'locate' => 'home#location'
  get 'choose/(:id)' => 'home#set_location'
end

app/models/user.rb
#encoding:utf-8
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  #include Devise::Async::Model # should be below call to `devise`
  # Setup accessible (or protected) attributes for your model
  validates :username , :length => {:in => 3..30 , :message => "用户名必须为3-30个字符"}
  has_attached_file :image_url,
     :styles => {
       :thumb=> "80x80#",
       :small  => "30x30>",
       :big  => "90x90>"}

  has_one  :store
  has_many :orders
  has_many :complaints ,:dependent => :destroy
  has_many :send_address
  #增加用户和收藏的级联关系的删除
  has_many :favorites , :dependent => :destroy
  has_many :stores, :through => :favorites
  #增加用户收藏的食品
  has_many :favorite_foods , :dependent => :destroy
  has_many :foods, :through => :favorite_foods
  has_many :messages ,:dependent => :destroy
  has_one :application , :dependent =>:destroy
  has_one :good_address, :dependent =>:destroy
  has_and_belongs_to_many :activities
  belongs_to :station_mail

  after_create :fresh_the_number

  #异步邮箱
  # handle_asynchronously :send_reset_password_instructions , :run_at => Proc.new { Time.now }
  # handle_asynchronously :send_confirmation_instructions  , :run_at => Proc.new { Time.now }
  # handle_asynchronously :send_on_create_confirmation_instructions  , :run_at => Proc.new { Time.now }
  def can_increment_sent_address?
    send_address.size<10? true:false
  end

  def self.store_hosts
    User.where(["is_store = 0"]).all
  end

  def self.locked_users
    User.where(["is_locked = 1"]).all
  end

  def all_my_favorate_id
    favorite_foods.map {|food| food.id}
  end

  #判断当前用户是否收藏了该店
  def is_constains_store?(fav_store_id)
    Favorite.where(:user_id => id).select(:store_id).all.map { |p| p.store_id }.include?(fav_store_id)
  end

  #判断当前用户是否收藏了该食品
  def is_constains_food?(fav_food_id)
    FavoriteFood.where(:user_id => id).select(:food_id).all.map { |p| p.food_id }.include?(fav_food_id)
  end

  def get_image_url(type="big")
    if image_url.exists?
      case type
      when "thumb"
        image_url.url(:thumb)
      when "small"
        image_url.url(:small)
      else
      image_url.url(:big)
      end
    else
      unless image_url_file_name.blank?
        image_url_file_name
      else
        CONFIG["user_image_miss"]
      end
    end
  end

  def all_un_complainted_orders
    array = []
    Order.where("is_complainted = 0 and user_id = ?" ,id).each do |order|
      array << order.order_number
    end
    array
  end

  def self.convert_email_to_users emails
    users = []
    emails.split(";").each do |email|
      users << User.find_by_email(email)
    end
    users
  end

  def self.numbers(refresh = false)
    User.count
  end

  def signin_number(refresh = false)
    redis_key = "users_signin_#{id}"
    if refresh || (!$redis.exists redis_key) || ($redis.get redis_key).blank?
        number = 0
        $redis.set(redis_key,number)
        number
    else
      $redis.get redis_key
    end
  end

  def signin_number=(number)
    redis_key = "users_signin_#{id}"
    $redis.set(redis_key,number)
  end

  def is_signed
    !ScoreHistories.where("user_id=? and  change_type = 1 and  DATE(created_at) = DATE('#{Time.now}')",id).blank?
  end

  def is_not_continuous
    ScoreHistories.where("user_id=? and  change_type = 1 and  DATE(created_at) = ('#{24.hour.ago.to_date}')",id).blank?
  end

  private

  def fresh_the_number
    redis_key = "users_number"
    $redis.set(redis_key,User.count)
  end

end

app/controllers/admins/users_controller.rb
#encoding : utf-8

class Admins::UsersController < AdminsController

     def index
     	 type = params[:type].to_i
       if type == 0
       		@users =  User.order("created_at desc").paginate(:page => params[:page], :per_page => 20)
       elsif type == 1
       	  @users =  User.where("is_locked =1").order("created_at desc").paginate(:page => params[:page], :per_page => 20)
       elsif type == 3
          @users =  User.order("integral desc").paginate(:page => params[:page], :per_page => 20)
       else
       	  @users =  User.where("is_locked =0").order("created_at desc").paginate(:page => params[:page], :per_page => 20)
       end
       @page = (params[:page].to_i==0? 1: params[:page].to_i)
     end

     def query
     	 if params[:type] == "email"
     	     @users =  User.where("email like ? ",'%'+params[:query]+'%').order("created_at desc").paginate(:page => params[:page], :per_page => 20)
     	 else 
     	 	   @users =  User.where("username like ? ",'%'+params[:query]+'%').order("created_at desc").paginate(:page => params[:page], :per_page => 20)
     	 end
     end

     def destroy
     	 @user = User.find(params[:id])
     	 if  @user && @user.destroy
     	 	   flash[:success] = "#{@user.username}删除成功."
     	 else
           flash[:error] = "系统原因导致操作不成功."
     	 end
     	 redirect_to admins_users_path
     end

     def is_locked
     	  @user = User.find(params[:user_id])
     	  type = (@user.is_locked==0? "锁定": "解锁")
     	 if  @user && @user.update_attributes({:is_locked=>(@user.is_locked-1).abs})
     	 	   flash[:success] = "账户#{@user.username}#{type}成功."
     	 else
           flash[:error] = "账户#{@user.username}#{type}不成功."
     	 end
     	  redirect_to admins_users_path(:page=>params[:page])
     end

     def history
     	
     end

     def export
     	
     end

     def do_export
     	   unless (params[:export].blank? || params[:export][:users].blank?)
     	   	  user_data_attr = params[:export][:users].keys
     	   	  select_str = user_data_attr.join(",").to_s
     	   	  all_user = User.select(select_str)
     	   	  header_hash ={"id"=>"编号","username"=>"用户名","email"=>"邮箱","created_at"=>"创建时间","is_locked"=>"状态"}
     	   	  header= []
     	   	  user_data_attr.each {|k| header << header_hash[k.to_s]}
     	      csv_helper({:header=>header,:values=>all_user.map{|e|e.instance_values["attributes"].values}})
     	   else
     	   	 redirect_to export_admins_users_path
     	   end
     end

     def show
        @user = User.find(params[:id])
         
     end


end

app/helpers/users_helper.rb
#encoding: utf-8
module UsersHelper
  
  def do_save_comments(value)
    value["line_item"].each do |k,v|
      @line_item = LineItem.find(v["line_item_id"])
      @line_item.rank = v["score"].to_i
      @line_item.content = v["content"]
      @line_item.save
      @food = @line_item.food
      @food.comment_number = @food.comment_number+@line_item.quantity
      @food.comment_score = @food.comment_score + @line_item.quantity*@line_item.rank
      @food.rank = @food.comment_score.to_f/@food.comment_number
      @food.save
    end
    
     value["orderinfo"].each do |k,v|
      @order = Order.find_order_by_number(v["order_id"])
      @order.rank = v["score"].to_i
      @order.comment = v["content"]
      @order.is_comment = 1
      @order.save
      @store = @order.store
      @store.sum_comment = @store.sum_comment+1
      @store.sum_score = @store.sum_score+@order.rank
      @store.rank =  @store.sum_score/@store.sum_comment.to_f
      @store.save
      @user = @order.user
      @user.integral = @user.integral + @order.total_price*10
      @user.save
    end
  end

  def the_activity_status(end_time)
      end_time < Time.now ? "已开奖" : "未开奖"
  end
  
end

app/views/admins/users/_list.html.erb
<div class="admin-breadcrumb">
  <ul class="breadcrumb">
        <li><a href="/admins">Home</a> <span class="divider">/</span></li>
        <li class="active"><%=controller_name%></li>
  </ul>
</div>

<ul class="nav nav-tabs">
      <li title="" rel="" class="icon index_collection_link active">
        <a class="pjax" href="/admins/users">
              <i class="icon-th-list"></i>
              <span>List</span>
        </a>
      </li>
        
      <li title="" rel="" class="icon export_collection_link ">
        <a class="pjax" href="/admins/users/export">
              <i class="icon-share"></i>
            <span>Export</span>
        </a>
      </li>
        
          <li title="" rel="" class="icon history_index_collection_link ">
            <a class="pjax" href="/admin/comment/history">
              <i class="icon-book"></i>
              <span>History</span>
            </a>
          </li>
        
<li class="dropdown" style="float:right">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">Selected items<b class="caret"></b></a>
      <ul class="dropdown-menu" style="left:auto; right:0;">
        <li><a href="/admins/users?type=2" >normal</a></li>
        <li><a href="/admins/users?type=1" >clocked</a></li>
        <li><a href="/admins/users?type=0" >everyone</a></li>
        <li><a href="/admins/users?type=3" >积分排序</a></li>
      </ul>
</li>
</ul>
<%=render :partial => 'admins/flash', :locals => {:flash => flash} %>
<div id="list">
  <%= form_tag '/admins/users/query', :method => :post, :class=> "pjax-form form-inline"%>
     <div class="well ">
          <select class="input-small " name="type">
            <option value ="email">邮箱</option>
            <option value ="username">用户名</option>
          </select>
        <input class=" " name="query" placeholder="Filter" type="search" value="">
          <button class="btn btn-primary"  type="submit">
            <i class="icon-white icon-refresh"></i>
            查询
          </button>
        </div>
 </form>

<table class="table table-condensed table-striped">
  <thead>
      <th class="header pjax headerSortDown id_field integer_type">编号</th>
      <th class="  commentable_field polymorphic_association_type">用户名</th>
      <th class="header pjax  content_field text_type">邮箱</th>
      <th class="header pjax  content_field text_type">积分</th>
      <th class="header pjax  created_at_field datetime_type">创建时间</th>
      <th class="header pjax  created_at_field datetime_type">状态</th>
      <th class="last shrink"></th>
      </tr>
  </thead>
<tbody>
  <% @users.each do |user|%>
        <tr>
            <td class="id_field integer_type"><%=user.id%></td>
            <td class="commentable_field polymorphic_association_type" title="<%=user.username%>">
              <a href="/admins/users/<%=user.id%>" class="pjax"><%=user.username%></a>
            </td>
            <td class="content_field text_type"> <%=user.email%></td>
            <td class="content_field text_type"> <%=user.integral%></td>
           <td class="created_at_field datetime_type"><%=user.created_at.localtime.to_s(:db)%></td>
           <td class="created_at_field datetime_type">
            <span class="label label-<%= user.is_locked==0? 'success':'important' %>">
              <%= user.is_locked==0? '使用中':'已锁定' %></span>
          </td>
        <td class="last links">
           <ul class="inline">
            <%= link_to raw('<i class="icon-remove"></i>'), admins_user_path(user),method: :delete, data: { confirm: 'Are you sure?' } , title: '删除' %>
              <%= link_to raw('<i class="icon-book"></i>'), admins_user_history_path(user), title: '历史' %>
              <%lock_class = (user.is_locked==0? '<i class="icon-lock"></i>': '<i class="icon-ok"></i>')%>
             <%= link_to   raw(lock_class), 
               admins_user_is_locked_path(user,:page=>@page), title:(user.is_locked==0? "锁定": "解锁") %>
          </ul>
        </td>
        </tr>
<%end%>

</tbody>
</table>

<div class="pagination">
    <ul> <%= will_paginate @users %> </ul>
</div>
</div>

app/views/admins/users/export.html.erb
<div class="admin-breadcrumb">
  <ul class="breadcrumb">
        <li><a href="#">Home</a> <span class="divider">/</span></li>
        <li><a href="/admins/users"><%=controller_name%></a> <span class="divider">/</span></li>
        <li class="active"><%=action_name%></li>
  </ul>
</div>

<ul class="nav nav-tabs">
      <li title="" rel="" class="icon index_collection_link">
        <a class="pjax" href="/admins/users">
              <i class="icon-th-list"></i>
              <span>List</span>
        </a>
      </li>
        
      <li title="" rel="" class="icon export_collection_link active">
        <a class="pjax" href="/admins/users/export">
              <i class="icon-share"></i>
            <span>Export</span>
        </a>
      </li>
        
       <li title="" rel="" class="icon history_index_collection_link ">
            <a class="pjax" href="/admin/comment/history">
              <i class="icon-book"></i>
              <span>History</span>
            </a>
      </li>

</ul>
<%=form_tag '/admins/users/do_export', :method => :post, :class=> "pjax-form form-inline"%>
<fieldset>
<legend>
  <i class='icon-chevron-down'></i>
			Select fields to export
</legend>
<div class='control-group'>
<label class='control-label' data-original-title='Click to reverse selection' onclick='jQuery(this).siblings(".controls").find("input").click()' rel='tooltip'>Fields from comments</label>
<div class='controls'>
	<input checked="checked" id="schema_only_id" name="export[users][id]" type="checkbox" value="id" />
	编号
	<input checked="checked" id="schema_methods_commentable_id" name="export[users][username]" type="checkbox" value="username" />
	用户名
	<input checked="checked" id="schema_methods_commentable_type" name="export[users][email]" type="checkbox" value="email" />
	邮箱

	<input checked="checked" id="schema_only_content" name="export[users][created_at]" type="checkbox" value="created_at" />
	创建时间

	<input checked="checked" id="schema_only_created_at" name="export[users][is_locked]" type="checkbox" value="is_locked" />
	状态
</div>
</div>
</fieldset>
<div class='form-actions'>
<input name='return_to' type='hidden' value='http://rails-admin-tb.herokuapp.com/admin/comment'>
	<button class='btn btn-primary' name='csv' type='submit'>
	 <i class='icon-white icon-ok'></i>
	    Export to csv
  </button>
</div>
</form>

app/views/admins/users/history.html.erb
safsa

app/views/admins/users/index.html.erb
<%=render "admins/users/list"%>

app/views/admins/users/query.html.erb
<%=render "admins/users/list"%>

app/views/admins/users/show.html.erb
<div class="admin-breadcrumb">
  <ul class="breadcrumb">
        <li><a href="/admins">Home</a> <span class="divider">/</span></li>
        <li><a href="/admins/ads"><%=controller_name%></a> <span class="divider">/</span></li>
        <li class="active"><%=action_name%></li>
  </ul>
</div>

<%=render :partial => 'admins/flash', :locals => {:flash => flash} %>

<ul class="nav nav-tabs">
      <li title="" rel="" class="icon index_collection_link ">
        <a class="pjax" href="/admins/users">
              <i class="icon-th-list"></i>
              <span>List</span>
        </a>
      </li>
      <li title="查看" rel="" class="icon export_collection_link active">
        <%=link_to raw('<i class="icon-plus"></i><span>Show</span>'),
                "#", :class => 'pjax'%>
      </li>
</ul>


<h1>用户详情</h1>
<table class="table table-bordered">
  <tr>
    <td>编号</td>
    <td>用户名</td>
    <td>邮件</td>
    <td>注册时间</td>
    <td>是否点过餐</td>
  </tr>
  <tr>
    <td><%= @user.id %></td>
    <td><%= @user.username %></td>
    <td><%= @user.email %></td>
    <td><%= @user.created_at.to_s(:db) %></td>
    <td><%= @user.orders.blank?? "no":"yes" %></td>
  </tr>
</table>